# Generated by Django 4.1 on 2024-12-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_borrow', '0003_borrowing_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
