# Generated by Django 4.1 on 2024-12-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_borrow", "0008_alter_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(max_length=2000),
        ),
    ]
